version: '3'
services:
  alpine:
    build:
      context: provisioning/bns
      dockerfile: Dockerfile
    container_name: bns_data
    volumes:
      - ../persistent-data/bns-data:/bns-data
    env_file:
      - ../.env
    command:  sh -c ./setup-bns.sh