version: "3"
services:
  stacks-node-follower:
    build:
      context: ./Dockerfiles/stacks-blockchain
    command: stacks-node start --config=/app/config/Config.toml
    restart: on-failure
    environment:
      STACKS_EVENT_OBSERVER: stacks-node-api:3700
      XBLOCKSTACK_DEBUG: 1
      RUST_BACKTRACE: 1
    volumes:
      - ./private-testnet/:/app/config
    depends_on:
      - bitcoind-fill-faucet
    networks:
    - stacks-blockchain
  explorer:
    image: blockstack/explorer
    container_name: explorer
    environment:
      - MOCKNET_API_SERVER=http://localhost:3999
    ports:
      - 3000:3000
    depends_on: 
      - stacks-node-api
    networks:
      - stacks-blockchain
  bitcoin:
    build:
      context: ./Dockerfiles/bitcoin
    ports:
      - "18443:18443"
      - "18444:18444"
    command: 
      -chain=regtest
      -disablewallet=0
      -printtoconsole
      -txindex=1
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=blockstack
      -rpcpassword=blockstack
    networks:
      - stacks-blockchain
  bitcoind-fill-faucet:
    image: "byrnedo/alpine-curl"
    depends_on:
      - bitcoin
    restart: on-failure
    command: |
      -f -u blockstack:blockstack --data-binary '{"jsonrpc": "1.0", "id":"c", "method": "generatetoaddress", "params": [110, "mrzLDS7LT3otAnpiRWGYkWipdnAZJaXAZQ"] }' -H 'content-type: text/plain;' http://bitcoin:18443/
    networks:
      - stacks-blockchain

