version: "3"
services:
  stacks-node-follower:
    image: blockstack/stacks-blockchain:feat-miner-control
    volumes:
      - ./private-testnet:/src/stacks-node
      # - ../persistent-data/stacks-node:/root/stacks-node/data
    environment:
      BLOCKSTACK_USE_TEST_GENESIS_CHAINSTATE: 1
      NOP_BLOCKSTACK_DEBUG: 1
  explorer:
    image: blockstack/explorer:latest
    container_name: explorer
    environment:
      - NEXT_PUBLIC_MAINNET_API_SERVER=http://stacks-node-api.stacks-blockchain:3999
      - NEXT_PUBLIC_TESTNET_API_SERVER=http://stacks-node-api.stacks-blockchain:3399
      - MOCKNET_API_SERVER=http://localhost:3999
      - TESTNET_API_SERVER=http://localhost:3999
    ports:
      - 3000:3000
    networks:
      - stacks-blockchain
  bitcoind:
    build:
      context: ./stacks-blockchain/bitcoin
    ports:
      - "18443:18443"
      - "18444:18444"
    command: 
      -chain=regtest
      -disablewallet=0
      -printtoconsole
      -txindex=1
      -server=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=blockstack
      -rpcpassword=blockstack
    networks:
      - stacks-blockchain
  bitcoind-fill-faucet:
    image: "byrnedo/alpine-curl"
    depends_on:
      - bitcoind
    restart: on-failure
    command: |
      -f -u blockstack:blockstack --data-binary '{"jsonrpc": "1.0", "id":"c", "method": "generatetoaddress", "params": [110, "mrzLDS7LT3otAnpiRWGYkWipdnAZJaXAZQ"] }' -H 'content-type: text/plain;' http://bitcoind:18443/
    networks:
      - stacks-blockchain

